name: Buddhism in the West
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2ebe2'
    - '#08585f'
    - '#000002'
    - '#a49d8c'
    - '#90453b'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
