name: Buddhism in the West
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eae5e4'
    - '#010a13'
    - '#576169'
    - '#9ba0a8'
    - '#b42d35'
  brandStrength: 0.30933274631388485
  lightness: 0.5846342965960503
  saturation: 0.9433370288461447
  rhythmicContrast: 0.6112070390954614
purpose: []
